### ISSUE TITLE
Tracking: Group Chat App

### ISSUE THREAD

**Issue by nplasterer** [xmtp-labs/xmtp-inbox-mobile#59]
### V1

- [ ] Remove V2 & Test Performance https://github.com/xmtp-labs/xmtp-inbox-mobile/pull/56
- [ ] [Grow Group size limits](https://github.com/xmtp/libxmtp/issues/701)
- [ ] Fix Testflight release
- [ ] Playstore release
- [ ] Support Push Notifications (iOS Entitlement) https://github.com/xmtp-labs/xmtp-inbox-mobile/issues/16
- [ ] Replace login with Privy
- [ ] Reactions https://github.com/xmtp-labs/xmtp-inbox-mobile/issues/7
- [ ] Replies https://github.com/xmtp-labs/xmtp-inbox-mobile/issues/30

### V2

- [ ] Pinned Frames Support
- [ ] Full App Redesign

**Comment by saulmc** [comment]
Took a spin through the app, added a few issues, separated must-haves from nice-to-haves.

**Comment by nplasterer** [comment]
@alexrisch Some of these features that you already support but might need some extra help like the adding and removing members permissions stuff that Cameron is going to need to do. Maybe we can put that behind a feature flag?

**Comment by saulmc** [comment]
@alexrisch added #69 / #84 (related?) to the V1 list -- definitely want this in for a bug bash

**Comment by alexrisch** [comment]
> @alexrisch added #69 / #84 (related?) to the V1 list -- definitely want this in for a bug bash

@saulmc Yes they are related
We were using some Thirdweb stuff after handling connecting a wallet, but both tickets will be finished in the same change
